2018-05-11 23:12:50,686 [INFO] __init__.py(40):Microblog startup
2018-05-11 23:26:56,572 [INFO] __init__.py(40):Microblog startup
2018-05-11 23:26:59,385 [ERROR] app.py(1560):Exception on /auth/login [GET]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\workspace\microblog3\microblog\app\auth\routes.py", line 41, in login
    return render_template('auth/login.html',title='Sign In',form=form)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\workspace\microblog3\microblog\app\templates\base.html", line 40, in template
    {% endblock %}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "E:\workspace\microblog3\microblog\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\workspace\microblog3\microblog\app\templates\base.html", line 40, in template
    {% endblock %}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 170, in parse_statements
    self.fail_eof(end_tokens)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 104, in fail_eof
    return self._fail_ut_eof(None, stack, lineno)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-05-11 23:28:27,095 [INFO] __init__.py(40):Microblog startup
2018-05-11 23:29:38,072 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:02:53,684 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:02:57,020 [ERROR] app.py(1560):Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\workspace\microblog3\microblog\app\routes.py", line 26, in index
    return render_template('index.html',title='Home', user=user, posts=posts)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\templating.py", line 134, in render_template
    context, ctx.app)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\templating.py", line 116, in _render
    rv = template.render(context)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\workspace\microblog3\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\workspace\microblog3\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "E:\workspace\microblog3\microblog\app\templates\base.html", line 27, in block "navbar"
    <li><a href="{{ url_for('explore') }}">Explore</a></li>
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'upload' instead?
2018-05-12 00:03:18,537 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:22:16,528 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:22:22,569 [ERROR] app.py(1560):Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\workspace\microblog3\microblog\app\routes.py", line 24, in index
    return render_template('index.html',title='Home', user=user, posts=posts)
NameError: name 'posts' is not defined
2018-05-12 00:24:21,231 [INFO] __init__.py(40):Microblog startup
