2018-05-12 00:29:54,970 [ERROR] app.py(1560):Exception on /auth/register [POST]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\workspace\microblog3\microblog\app\auth\routes.py", line 23, in register
    return redirect(url_for('login'))
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\helpers.py", line 333, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1805, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\helpers.py", line 323, in url_for
    force_external=external)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\werkzeug\routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'login'. Did you mean 'auth.login' instead?
2018-05-12 00:31:56,285 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:32:32,680 [ERROR] app.py(1560):Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\workspace\microblog3\microblog\app\routes.py", line 18, in index
    if validate_on_submit():
NameError: name 'validate_on_submit' is not defined
2018-05-12 00:33:11,427 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:33:34,354 [ERROR] app.py(1560):Exception on /index [POST]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\workspace\microblog3\microblog\app\routes.py", line 19, in index
    user.post.body = form.post.data
AttributeError: 'PostForm' object has no attribute 'post'
2018-05-12 00:39:15,995 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:42:20,361 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:47:41,514 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:48:11,395 [INFO] routes.py(22):user ericguanwy registered.
2018-05-12 00:50:46,125 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:52:25,828 [INFO] __init__.py(40):Microblog startup
2018-05-12 00:55:39,766 [INFO] __init__.py(40):Microblog startup
2018-05-12 01:07:01,219 [INFO] __init__.py(40):Microblog startup
2018-05-12 01:07:04,506 [ERROR] app.py(1560):Exception on /index [GET]
Traceback (most recent call last):
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "E:\workspace\microblog3\microblog\app\routes.py", line 25, in index
    return render_template('index.html',title='Home', user=user, posts=posts, form= form)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\flask\templating.py", line 133, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\workspace\microblog3\microblog\app\templates\index.html", line 6, in template
    {% elif current_user == user %}
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 896, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 878, in subparse
    rv = self.parse_statement()
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "E:\ProgramFiles\Anaconda3\lib\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'elif'. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2018-05-12 01:07:36,486 [INFO] __init__.py(40):Microblog startup
2018-05-12 08:33:54,371 [INFO] __init__.py(40):Microblog startup
2018-05-12 08:34:57,200 [INFO] __init__.py(40):Microblog startup
2018-05-12 08:35:23,685 [INFO] __init__.py(40):Microblog startup
2018-05-12 08:37:11,060 [INFO] __init__.py(40):Microblog startup
2018-05-12 09:08:24,190 [INFO] __init__.py(40):Microblog startup
2018-05-12 09:08:31,456 [INFO] __init__.py(40):Microblog startup
2018-05-12 09:08:36,361 [INFO] __init__.py(40):Microblog startup
2018-05-12 09:08:45,613 [INFO] __init__.py(40):Microblog startup
2018-05-12 09:08:53,563 [INFO] __init__.py(40):Microblog startup
